/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 17:20:46 GMT 2024
 */

package poligono;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import poligono.Ponto;
import poligono.Retangulo;

@RunWith(EvoRunner.class) 
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)

public class Retangulo_ESTest extends Retangulo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ponto ponto0 = new Ponto();
      Ponto ponto1 = new Ponto(2.0, 2.0);
      Retangulo retangulo0 = new Retangulo(ponto0, ponto0, ponto1, ponto0);
      double double0 = retangulo0.areaQuadrado();
      assertEquals(5.656854249492381, retangulo0.perimetro(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Ponto ponto0 = new Ponto(1.0, 1.0);
      Ponto ponto1 = new Ponto();
      Retangulo retangulo0 = new Retangulo(ponto0, ponto1, ponto0, ponto1);
      double double0 = retangulo0.areaQuadrado();
      assertEquals(2.0000000000000004, double0, 0.01);
      assertEquals(5.656854249492381, retangulo0.perimetro(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Retangulo retangulo0 = null;
      try {
        retangulo0 = new Retangulo((Ponto) null, (Ponto) null, (Ponto) null, (Ponto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("poligono.Retangulo", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Retangulo retangulo0 = new Retangulo();
      // Undeclared exception!
      try { 
        retangulo0.areaQuadrado();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Ponto ponto0 = new Ponto();
      Retangulo retangulo0 = new Retangulo(ponto0, ponto0, ponto0, ponto0);
      Retangulo retangulo1 = retangulo0.clone();
      assertEquals(0.0, retangulo1.perimetro(), 0.01);
  }
}
