/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 14 17:50:50 GMT 2024
 */

package poligono;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import poligono.NaoConvexoException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NaoConvexoException_ESTest extends NaoConvexoException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NaoConvexoException naoConvexoException0 = new NaoConvexoException();
  }
}
