/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 14 17:51:26 GMT 2024
 */

package poligono;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import poligono.Ponto;
import poligono.Retangulo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Retangulo_ESTest extends Retangulo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ponto ponto0 = new Ponto();
      Ponto ponto1 = new Ponto((-1367.83), (-1367.83));
      Retangulo retangulo0 = new Retangulo(ponto0, ponto0, ponto1, ponto0);
      double double0 = retangulo0.areaQuadrado();
      assertEquals(3868.807474041581, retangulo0.perimetro(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Ponto ponto0 = new Ponto(2909.671217, 2909.671217);
      Ponto ponto1 = new Ponto();
      Retangulo retangulo0 = new Retangulo(ponto0, ponto1, ponto0, ponto0);
      double double0 = retangulo0.areaQuadrado();
      assertEquals(1.6932373182076517E7, double0, 0.01);
      assertEquals(8229.792994256057, retangulo0.perimetro(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Retangulo retangulo0 = null;
      try {
        retangulo0 = new Retangulo((Ponto) null, (Ponto) null, (Ponto) null, (Ponto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("poligono.Retangulo", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Retangulo retangulo0 = new Retangulo();
      // Undeclared exception!
      try { 
        retangulo0.areaQuadrado();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Ponto ponto0 = new Ponto();
      Retangulo retangulo0 = new Retangulo(ponto0, ponto0, ponto0, ponto0);
      Retangulo retangulo1 = retangulo0.clone();
      assertFalse(retangulo1.equals((Object)retangulo0));
  }
}
