package business.Station.enums;

public enum TypesOfUniversalServices {
    REPLACING_TIRES,
    CALIBRATING_WHEELS,
    ALIGNING_STEERING,
    REPLACING_INJECTORS,
    REPLACING_BRAKE_PADS,
    CHANGING_BRAKE_OIL,
    CLEANING_INTERIOR,
    CLEANING_EXTERIOR,
    REPLACING_CABIN_AIR_FILTER
}
