/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 23:40:28 GMT 2024
 */

package TP2;

import org.junit.Test;
import static org.junit.Assert.*;
import TP2.EncomendaDevolucaoImpossivelException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class EncomendaDevolucaoImpossivelException_ESTest extends EncomendaDevolucaoImpossivelException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EncomendaDevolucaoImpossivelException encomendaDevolucaoImpossivelException0 = new EncomendaDevolucaoImpossivelException("");
  }
}
