/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 23:18:23 GMT 2024
 */

package TP2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import TP2.Artigo;
import TP2.Encomenda;
import TP2.Estado;
import TP2.Gestor_Artigos;
import TP2.Padrao;
import TP2.Tamanho;
import java.nio.charset.Charset;
import java.time.Clock;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Gestor_Artigos_ESTest extends Gestor_Artigos_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean(true);
      gestor_Artigos0.criar_artigo_mala(" Id do vendedor: ", "O artigo ", 0.0, false, (-1840700267), 3384, 0L, 3384, 3, "0_d", 3, boolean0, (-162.1F));
      String string0 = gestor_Artigos0.pesquisar_artigos_ano_colecao(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_dimensão_mala((-2139192203));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3128);
      gestor_Artigos0.criar_artigo_sapatilhas("dU5^vXCab5WQt>", " n\u00E3o existe!", 0.0, false, 3128, 0, long0, 0, 0, false, "", 815, false, 0.0);
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(3128);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long((-1L));
      Tamanho tamanho0 = Tamanho.M;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("TP2.Encomenda", "TP2.Gestor_Artigos", 1884, true, 1336, 1336, (-417L), long0, tamanho0, padrao0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("A1");
      double double0 = gestor_Artigos0.vendaTotal(linkedHashSet0, localDate0);
      assertEquals(1884.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = Boolean.valueOf(true);
      gestor_Artigos0.criar_artigo_mala("", "", 10.0, false, 0, 0, (-3003L), 0, (-100), "", (-100), boolean0, 0.0F);
      gestor_Artigos0.alteraDataToInicio("A1");
      assertEquals(0.25, gestor_Artigos0.getTaxaUsado(), 0.01);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      long long1 = gestor_Artigos0.tirar_disponivel_artigo("A1");
      assertEquals(0L, long1);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long(973);
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("", "sBHZ", 973, false, (-845), (-2139192203), 973, long0, tamanho0, padrao0);
      long long1 = gestor_Artigos0.tirar_disponivel_artigo("A1");
      assertEquals(973L, long1);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), 1L, 1L, (-1483), "eo?_b)@'i<", (-1483), boolean0, 1L);
      Long long0 = gestor_Artigos0.id_artigo_para_id_vendedor("A1");
      assertEquals(1L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "wUAb<3P^2RU.+>5<", (-1483), boolean0, (-294L));
      Long long0 = gestor_Artigos0.id_artigo_para_id_vendedor("A1");
      assertEquals((-294L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala("", "T-shirt:: {", 0.0, true, (-1), (-1), (-966), (-1), (-1), " Cor: ", (-1), boolean0, (-1));
      Long long0 = new Long(0L);
      gestor_Artigos0.criar_artigo_sapatilhas((String) null, (String) null, 0.0, true, (-966), (-966), long0, (-966), 4, true, "\n", (-2138754037), false, 4);
      Long long1 = gestor_Artigos0.id_artigo_para_id_transportadora("A2");
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3128);
      gestor_Artigos0.criar_artigo_sapatilhas("dU5^vXCab5WQt>", " n\u00E3o existe!", 0.0, false, 3128, 0, long0, 0, 0, false, "", 815, false, 0.0);
      Long long1 = gestor_Artigos0.id_artigo_para_id_transportadora("A1");
      assertEquals(3128L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = Boolean.valueOf("J#S-v");
      gestor_Artigos0.criar_artigo_mala(" -y%zC'yXE", "J#S-v", 4406.9, false, (-1890), 5, (-5L), 5, 5, "", 690, boolean0, (-1890));
      Long long0 = gestor_Artigos0.id_artigo_para_id_transportadora("A1");
      assertEquals((-5L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Gestor_Artigos.setTaxaUsado(0.0);
      double double0 = Gestor_Artigos.getTaxaUsado();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo((-356));
      double double0 = Gestor_Artigos.getTaxaNovo();
      assertEquals((-356.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      Long long0 = new Long(0);
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, 0, (-1483), (-1483), long0, tamanho0, padrao0);
      long long1 = gestor_Artigos0.colocar_disponivel_artigo("A2");
      assertEquals(0L, long1);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.getLong("'_Uv4=X^b<,xAt+K>>", (long) 1);
      Tamanho tamanho0 = Tamanho.S;
      Padrao padrao0 = Padrao.liso;
      gestor_Artigos0.criar_artigo_tshirt(" Id do vendedor: ", (String) null, 1235.783747912826, false, 1, (-1840700267), (-1L), long0, tamanho0, padrao0);
      long long1 = gestor_Artigos0.colocar_disponivel_artigo("A1");
      assertEquals(1L, long1);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      String string0 = gestor_Artigos0.artigoToString("A1");
      assertEquals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: 9 Marca:  n\u00E3o existe! Pre\u00E7o base: 0.0 Novo: true Estado de uso: 3154 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 3154 Id do vendedor: 0 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 815 Premium: true Desconto: 0.0}", string0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.setArtigos((Map<String, Artigo>) null);
      // Undeclared exception!
      try { 
        gestor_Artigos0.vintageFaturou();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, 0, (-1483), (-1483), long0, tamanho0, padrao0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_novo_tshirt((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala(" Novo: ", " Novo: ", 0.01, true, (-1840700267), (-1840700267), (-1840700267), (-1840700267), 3, " -y%zC'yXE", (-1675), boolean0, 0.0F);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_novo_mala((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("*");
      gestor_Artigos0.criar_artigo_mala("\u20AC ", "T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: O artgo  Marca: O artgo  Pre\u00E7o base: -1.0 Novo: false Estado de uso: 1 N\u00FAmero de utilizadores: -1840700267 Disponivel: true Id da transportadora: -1 Id do vendedor: 1 } Tamanho: S Padr\u00E3o: liso}\n", (-39L), false, 2793, 2231, (-39L), (-757L), 1, (String) null, (-1483), boolean0, 0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_material("BIYZk");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("sBHZ", (String) null, 0.0, false, (-2139192203), (-1), (-4), long0, tamanho0, padrao0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_marca_tshirt("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean(true);
      gestor_Artigos0.criar_artigo_mala("", "Mz>9/7#=", 707.53006435977, true, (-2147483622), 562, (-2147483622), (-1661L), (-2021161078), "Mz>9/7#=", (-2021161078), boolean0, 562);
      LocalDate localDate0 = MockLocalDate.now();
      // Undeclared exception!
      gestor_Artigos0.mostrar_gestor(localDate0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.mostrar_gestor((LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Sapatilha", e);
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_tshirt("^]<qvs;?]piC", "$VALUES", 2348.98538496, true, (-642), 0, (-873L), (Long) null, tamanho0, padrao0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_sapatilhas((String) null, "^4cS>gqkPb'jB", (-118.92289735), false, (-1982), (-1982), (Long) null, (-1982), 3849, true, "1NFM!p", 3849, true, 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_mala("Expedida", "", 579.8746139549582, false, 0, 0, (-1L), 0, 0, "M", 3, (Boolean) null, 69.5412F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Gestor_Artigos gestor_Artigos1 = null;
      try {
        gestor_Artigos1 = new Gestor_Artigos(gestor_Artigos0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      // Undeclared exception!
      try { 
        gestor_Artigos0.entreDatas(set0, (LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Locale locale0 = Locale.ITALIAN;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      int int0 = gestor_Artigos0.entreDatas(set0, localDate0, localDate0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      double double0 = gestor_Artigos0.vintageFaturou();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long((-1L));
      Tamanho tamanho0 = Tamanho.M;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("TP2.Encomenda", "TP2.Gestor_Artigos", 0.0, true, 1336, 1336, (-417L), long0, tamanho0, padrao0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("A1");
      double double0 = gestor_Artigos0.precoFaturouTempo(linkedHashSet0, localDate0, localDate0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("A1");
      // Undeclared exception!
      try { 
        gestor_Artigos0.precoFaturouTempo(linkedHashSet0, localDate0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      LocalDate localDate0 = MockLocalDate.now();
      Charset charset0 = Charset.defaultCharset();
      Set<String> set0 = charset0.aliases();
      // Undeclared exception!
      try { 
        gestor_Artigos0.precoFaturou(set0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Locale locale0 = Locale.US;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-230L));
      double double0 = gestor_Artigos0.precoFaturou(set0, localDate0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("A1");
      // Undeclared exception!
      try { 
        gestor_Artigos0.vendaTotal(linkedHashSet0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      double double0 = gestor_Artigos0.vendaTotal(linkedHashSet0, localDate0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      encomenda0.adicionaArtigo("Y4_ISp0Tr?`9E");
      // Undeclared exception!
      try { 
        gestor_Artigos0.alteraData(encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      gestor_Artigos0.alteraData(encomenda0);
      assertEquals(Estado.Pendente, encomenda0.getEstado());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      long long1 = gestor_Artigos0.colocar_disponivel_artigo("A2");
      assertEquals((-39L), long1);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      try { 
        gestor_Artigos0.colocar_disponivel_artigo("T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: O artigo  Marca: null Pre\u00E7o base: -1.0 Novo: false Estado de uso: 1 N\u00FAmero de utilizadores: -1840700267 Disponivel: true Id da transportadora: -1 Id do vendedor: 1 } Tamanho: S Padr\u00E3o: liso}\n");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: O artigo  Marca: null Pre\u00E7o base: -1.0 Novo: false Estado de uso: 1 N\u00FAmero de utilizadores: -1840700267 Disponivel: true Id da transportadora: -1 Id do vendedor: 1 } Tamanho: S Padr\u00E3o: liso}
         //  n\u00E3o existe!
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      try { 
        gestor_Artigos0.tirar_disponivel_artigo("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo  n\u00E3o existe!
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH(a{48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 98.06488912792511, false, (-1486), (-1486), (-294L), (-294L), (-1486), "eo?_b)@'i<", (-1486), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_ano_colecao((-1486));
      assertEquals("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: 98.06488912792511 Novo: false Estado de uso: -1486 N\u00FAmero de utilizadores: -1486 Disponivel: true Id da transportadora: -294 Id do vendedor: -294 } Dimens\u00E3o: -1486 Material: eo?_b)@'i< Ano da Cole\u00E7\u00E3o: -1486 Premium: false Valoriza\u00E7\u00E3o: -294.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Padrao padrao0 = Padrao.liso;
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      String string0 = gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, 0, (-1483), (-1483), long0, tamanho0, padrao0);
      String string1 = gestor_Artigos0.pesquisar_artigos_ano_colecao(584);
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "wUAb<3P^2RU.+>5<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_ano_colecao(584);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("Ub5?Kcc$*@Q*0S-l");
      gestor_Artigos0.criar_artigo_mala("Ub5?Kcc$*@Q*0S-l", "Ub5?Kcc$*@Q*0S-l", (-1670.44867161), true, 0, 633, 0L, (-598L), 0, "Ub5?Kcc$*@Q*0S-l", 633, boolean0, 0.0F);
      String string0 = gestor_Artigos0.pesquisar_artigos_material("Ub5?Kcc$*@Q*0S-l");
      assertEquals("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Ub5?Kcc$*@Q*0S-l Marca: Ub5?Kcc$*@Q*0S-l Pre\u00E7o base: -1670.44867161 Novo: true Estado de uso: 0 N\u00FAmero de utilizadores: 633 Disponivel: true Id da transportadora: 0 Id do vendedor: -598 } Dimens\u00E3o: 0 Material: Ub5?Kcc$*@Q*0S-l Ano da Cole\u00E7\u00E3o: 633 Premium: false Valoriza\u00E7\u00E3o: 0.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Padrao padrao0 = Padrao.liso;
      Long long0 = new Long((-282L));
      Tamanho tamanho0 = Tamanho.L;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, 0, (-1483), (-1483), long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_material("BIYZk");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("*");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-282L), (-282L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-282L));
      String string0 = gestor_Artigos0.pesquisar_artigos_material("BIYZk");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      Padrao padrao1 = Padrao.liso;
      String string0 = gestor_Artigos0.pesquisar_artigos_padrao(padrao1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      gestor_Artigos0.tirar_disponivel_artigo("A1");
      String string0 = gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: 4y,+DP%zmN%Y@xCi8 Marca:  Pre\u00E7o base: 2657.923882300646 Novo: true Estado de uso: -22 N\u00FAmero de utilizadores: -1483 Disponivel: true Id da transportadora: -1483 Id do vendedor: -39 } Tamanho: L Padr\u00E3o: palmeiras}\n", string0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      String string0 = gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      Padrao padrao0 = Padrao.palmeiras;
      String string1 = gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      String string0 = gestor_Artigos0.pesquisar_artigos_cor("");
      assertEquals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: 9 Marca:  n\u00E3o existe! Pre\u00E7o base: 0.0 Novo: true Estado de uso: 3154 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 3154 Id do vendedor: 0 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 815 Premium: true Desconto: 0.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.liso;
      gestor_Artigos0.criar_artigo_tshirt("", " n\u00E3o existe!", 0.0, true, 325, 325, 0L, long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_cor("sx.<BZ");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n2\u00E3o existe!", 0.0, true, 3154, 1, long0, 1, 1, true, "", 815, true, 0.0);
      String string0 = gestor_Artigos0.pesquisar_artigos_cor("sx.<BZ");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("*");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-282L), (-282L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-282L));
      String string0 = gestor_Artigos0.pesquisar_artigos_dimensão_mala((-1483));
      assertEquals("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: 100.0 Novo: false Estado de uso: -1483 N\u00FAmero de utilizadores: -1483 Disponivel: true Id da transportadora: -282 Id do vendedor: -282 } Dimens\u00E3o: -1483 Material: eo?_b)@'i< Ano da Cole\u00E7\u00E3o: -1483 Premium: false Valoriza\u00E7\u00E3o: -282.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      String string0 = gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      String string1 = gestor_Artigos0.pesquisar_artigos_dimensão_mala((-22));
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_dimensão_mala((-22));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Padrao padrao0 = Padrao.liso;
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, 0, (-1483), (-1483), long0, tamanho0, padrao0);
      Tamanho tamanho1 = Tamanho.M;
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      gestor_Artigos0.tirar_disponivel_artigo("A1");
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "wUAb<3P^2RU.+>5<", (-1483), boolean0, (-294L));
      Tamanho tamanho0 = Tamanho.L;
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Z4CV'm Marca: sBHZ Pre\u00E7o base: -4.0 Novo: false Estado de uso: -845 N\u00FAmero de utilizadores: -2139192203 Disponivel: true Id da transportadora: -4 Id do vendedor: -4 } Tamanho: L Padr\u00E3o: palmeiras}\n", string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      assertEquals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: 9 Marca:  n\u00E3o existe! Pre\u00E7o base: 0.0 Novo: true Estado de uso: 3154 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 3154 Id do vendedor: 0 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 815 Premium: true Desconto: 0.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n2\u00E3o existe!", 0.0, true, 3154, 1, long0, 1, 1, true, "", 815, true, 0.0);
      String string0 = gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      String string0 = gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string1 = gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas((-1483));
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "wUAb<3P^2RU.+>5<", (-1483), boolean0, (-294L));
      Boolean boolean1 = Boolean.TRUE;
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_mala(boolean1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "wUAb<3P^2RU.+>5<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      assertEquals("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: 100.0 Novo: false Estado de uso: -1483 N\u00FAmero de utilizadores: -1483 Disponivel: true Id da transportadora: -294 Id do vendedor: -294 } Dimens\u00E3o: -1483 Material: wUAb<3P^2RU.+>5< Ano da Cole\u00E7\u00E3o: -1483 Premium: false Valoriza\u00E7\u00E3o: -294.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      Boolean boolean0 = new Boolean("sBHZ");
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      Boolean boolean0 = Boolean.FALSE;
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Z4CV'm Marca: sBHZ Pre\u00E7o base: -4.0 Novo: false Estado de uso: -845 N\u00FAmero de utilizadores: -2139192203 Disponivel: true Id da transportadora: -4 Id do vendedor: -4 } Tamanho: L Padr\u00E3o: palmeiras}\n", string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      gestor_Artigos0.tirar_disponivel_artigo("A1");
      Boolean boolean0 = new Boolean("sBHZ");
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(0);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "\"", 3154, true, 0.0);
      Boolean boolean0 = new Boolean(true);
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean0);
      assertEquals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: 9 Marca:  n\u00E3o existe! Pre\u00E7o base: 0.0 Novo: true Estado de uso: 3154 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 0 Id do vendedor: 0 } Tamanho: 0 Atacadores: true Cor: \" Data da Cole\u00E7\u00E3o: 3154 Premium: true Desconto: 0.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(0);
      Boolean boolean0 = new Boolean("OrY,");
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.liso;
      gestor_Artigos0.criar_artigo_tshirt("", ": no xxse!", 0.0, true, 325, 325, 0, long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(0);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "\"", 3154, true, 0.0);
      Boolean boolean0 = new Boolean("OrY,");
      String string0 = gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1483), (-1483), (-294L), (-294L), (-1483), "wUAb<3P^2RU.+>5<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_mala("");
      assertEquals("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: 100.0 Novo: false Estado de uso: -1483 N\u00FAmero de utilizadores: -1483 Disponivel: true Id da transportadora: -294 Id do vendedor: -294 } Dimens\u00E3o: -1483 Material: wUAb<3P^2RU.+>5< Ano da Cole\u00E7\u00E3o: -1483 Premium: false Valoriza\u00E7\u00E3o: -294.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      String string0 = gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      String string1 = gestor_Artigos0.pesquisar_artigos_marca_mala("'N:tdH({48 f)JZ`");
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_mala("'N:tdH({48 f)JZ`");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Padrao padrao0 = Padrao.liso;
      Long long0 = new Long((-282L));
      Tamanho tamanho0 = Tamanho.L;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, 0, (-1483), (-1483), long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_tshirt("");
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: 4y,+DP%zmN%Y@xCi8 Marca:  Pre\u00E7o base: 2657.923882300646 Novo: true Estado de uso: 0 N\u00FAmero de utilizadores: -1483 Disponivel: true Id da transportadora: -1483 Id do vendedor: -282 } Tamanho: L Padr\u00E3o: liso}\n", string0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      String string0 = gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      gestor_Artigos0.tirar_disponivel_artigo("A1");
      String string1 = gestor_Artigos0.pesquisar_artigos_marca_tshirt("");
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = Long.valueOf((-39L));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("4y,+DP%zmN%Y@xCi8", "", 2657.923882300646, true, (-22), (-1483), (-1483), long0, tamanho0, padrao0);
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_tshirt("A2");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      String string0 = gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string1 = gestor_Artigos0.pesquisar_artigos_marca_tshirt("A2");
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(2481L);
      gestor_Artigos0.criar_artigo_sapatilhas((String) null, "", 0.0, true, (-1489), (-1489), long0, 2481L, 50, true, "?F+V=", (-1489), true, 2481L);
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_sapatilha("");
      assertEquals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: null Marca:  Pre\u00E7o base: 0.0 Novo: true Estado de uso: -1489 N\u00FAmero de utilizadores: -1489 Disponivel: true Id da transportadora: 2481 Id do vendedor: 2481 } Tamanho: 50 Atacadores: true Cor: ?F+V= Data da Cole\u00E7\u00E3o: -1489 Premium: true Desconto: 2481.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3154);
      gestor_Artigos0.criar_artigo_sapatilhas("9", " n\u00E3o existe!", 0.0, true, 3154, 0, long0, 0, 0, true, "", 815, true, 0.0);
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_sapatilha("?q+$\"cN#`zri~");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 99.89129884161089, false, (-1483), (-1483), (-294L), (-294L), (-1483), "eo?_b)@'i<", (-1483), boolean0, (-294L));
      String string0 = gestor_Artigos0.pesquisar_artigos_marca_sapatilha("Artigo invalido");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      Gestor_Artigos gestor_Artigos1 = new Gestor_Artigos();
      boolean boolean0 = gestor_Artigos0.equals(gestor_Artigos1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      boolean boolean0 = gestor_Artigos0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      boolean boolean0 = gestor_Artigos0.equals(gestor_Artigos0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Object object0 = new Object();
      boolean boolean0 = gestor_Artigos0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      boolean boolean0 = gestor_Artigos0.pesquisar_artigo_id("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("'N:tdH({48 f)JZ`");
      gestor_Artigos0.criar_artigo_mala("", "", 100.0, false, (-1486), (-1486), (-286L), (-286L), (-1486), "eo?_b)@'i<", (-1486), boolean0, (-286L));
      boolean boolean1 = gestor_Artigos0.pesquisar_artigo_id("A1");
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-230L));
      gestor_Artigos0.tirar_disponivel_artigo("A1");
      String string0 = gestor_Artigos0.mostrar_gestor(localDate0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long((-1L));
      Tamanho tamanho0 = Tamanho.M;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("TP2.Encomenda", "TP2.Gestor_Artigos", 0.0, true, 1336, 1336, (-417L), long0, tamanho0, padrao0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      String string0 = gestor_Artigos0.mostrar_gestor(localDate0);
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: TP2.Encomenda Marca: TP2.Gestor_Artigos Pre\u00E7o base: 0.0 Novo: true Estado de uso: 1336 N\u00FAmero de utilizadores: 1336 Disponivel: true Id da transportadora: -417 Id do vendedor: -1 } Tamanho: M Padr\u00E3o: palmeiras} Pre\u00E7o atual: 0.00\u20AC \n\n", string0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(3128);
      gestor_Artigos0.criar_artigo_sapatilhas("dU5^vXCab5WQt>", " n\u00E3o existe!", 0.0, false, 3128, 0, long0, 0, 0, false, "", 815, false, 0.0);
      String string0 = gestor_Artigos0.toString();
      assertEquals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: dU5^vXCab5WQt> Marca:  n\u00E3o existe! Pre\u00E7o base: 0.0 Novo: false Estado de uso: 3128 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 3128 Id do vendedor: 0 } Tamanho: 0 Atacadores: false Cor:  Data da Cole\u00E7\u00E3o: 815 Premium: false Desconto: 0.0}\n", string0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = gestor_Artigos0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(0.0);
      double double0 = Gestor_Artigos.getTaxaNovo();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("Z4CV'm", "sBHZ", (-4), false, (-845), (-2139192203), (-4), long0, tamanho0, padrao0);
      Map<String, Artigo> map0 = gestor_Artigos0.getArtigos();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      double double0 = Gestor_Artigos.getTaxaNovo();
      assertEquals(0.5, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString(":~9a5yugkvAuR<EF^cu");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long((-4));
      gestor_Artigos0.criar_artigo_sapatilhas("sBHZ", (String) null, 2, false, (-4), (-4), long0, (-1101L), (-845), false, "sBHZ", (-4), false, 0.5);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_marca_sapatilha("TP2.Gestor_Artigos");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Gestor_Artigos.setTaxaUsado((-1.0));
      double double0 = Gestor_Artigos.getTaxaUsado();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Map<String, Artigo> map0 = gestor_Artigos0.getArtigos();
      gestor_Artigos0.setArtigos(map0);
      assertEquals(0.25, gestor_Artigos0.getTaxaUsado(), 0.01);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_vendedor("A1");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      // Undeclared exception!
      try { 
        gestor_Artigos0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      double double0 = Gestor_Artigos.getTaxaUsado();
      assertEquals(0.25, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_transportadora("Ub5?Kcc$*@Q*0S-l");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      // Undeclared exception!
      try { 
        gestor_Artigos0.alteraDataToInicio("h>,/Sn)eaUB91+!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Gestor_Artigos", e);
      }
  }
}
