/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 23:24:49 GMT 2024
 */

package TP2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import TP2.Artigo;
import TP2.Encomenda;
import TP2.GestorEncomendas;
import TP2.Gestor_Artigos;
import TP2.Gestor_Transportadoras;
import TP2.Gestor_Utilizadores;
import TP2.Menu;
import TP2.Parsing;
import TP2.Transportadora;
import TP2.Vintage;
import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parsing_ESTest extends Parsing_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0, 0);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      String[] stringArray0 = new String[9];
      parsing0.venderTshit(123456L, (LocalDate) null, stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Menu menu0 = new Menu();
      LocalDate localDate0 = MockLocalDate.now();
      String[] stringArray0 = new String[8];
      Parsing parsing0 = new Parsing((Vintage) null, menu0);
      parsing0.venderSapatilha(123456L, localDate0, stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Vintage vintage0 = Vintage.load();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      String[] stringArray0 = new String[8];
      parsing0.venderMala(1L, (LocalDate) null, stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing((Vintage) null, menu0);
      Vintage vintage0 = parsing0.getVintage();
      assertNull(vintage0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      HashMap<Long, Transportadora> hashMap0 = new HashMap<Long, Transportadora>();
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras(hashMap0);
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Vintage vintage1 = parsing0.getVintage();
      assertSame(vintage1, vintage0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Vintage vintage0 = Vintage.load();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Vintage vintage1 = parsing0.getVintage();
      assertSame(vintage1, vintage0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Vintage vintage0 = Vintage.load();
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      Menu menu0 = parsing0.getMenu();
      assertNull(menu0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Vintage vintage0 = new Vintage((Gestor_Artigos) null, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, (Menu) null, 0);
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      String[] stringArray0 = new String[8];
      // Undeclared exception!
      try { 
        parsing0.venderTshit(0, (LocalDate) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Vintage vintage0 = new Vintage((Gestor_Artigos) null, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, (Menu) null, 0);
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      String[] stringArray0 = new String[8];
      // Undeclared exception!
      try { 
        parsing0.venderSapatilha(0, (LocalDate) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas();
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, (Menu) null, 70);
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      Period period0 = Period.ofMonths(70);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        parsing0.venderMala(1L, localDate0, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing((Vintage) null, menu0);
      // Undeclared exception!
      try { 
        parsing0.leitura_ficheiro("", (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Vintage vintage0 = Vintage.load();
      Parsing parsing0 = new Parsing(vintage0, (Menu) null);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "S";
      // Undeclared exception!
      try { 
        parsing0.adicionar_comando(stringArray0, (LocalDate) null);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"S\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0, 1);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      // Undeclared exception!
      try { 
        parsing0.adicionar_comando((String[]) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Parsing parsing0 = new Parsing((Vintage) null, (Menu) null);
      String[] stringArray0 = new String[0];
      LocalDate localDate0 = MockLocalDate.ofEpochDay(123456L);
      // Undeclared exception!
      try { 
        parsing0.adicionar_comando(stringArray0, localDate0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("TP2.Parsing", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0, 1);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      parsing0.setVintage(vintage0);
      assertEquals(1L, vintage0.getUtilizador());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Vintage vintage0 = new Vintage();
      Menu menu0 = new Menu();
      Parsing parsing0 = new Parsing(vintage0, menu0);
      parsing0.setMenu(menu0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0, 1);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Vintage vintage1 = parsing0.getVintage();
      assertSame(vintage0, vintage1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Gestor_Utilizadores gestor_Utilizadores0 = new Gestor_Utilizadores();
      HashMap<Long, Encomenda> hashMap0 = new HashMap<Long, Encomenda>();
      GestorEncomendas gestorEncomendas0 = new GestorEncomendas(hashMap0);
      Gestor_Transportadoras gestor_Transportadoras0 = new Gestor_Transportadoras();
      Menu menu0 = new Menu();
      Vintage vintage0 = new Vintage(gestor_Artigos0, gestor_Utilizadores0, gestorEncomendas0, gestor_Transportadoras0, menu0, 1);
      Parsing parsing0 = new Parsing(vintage0, menu0);
      Menu menu1 = parsing0.getMenu();
      assertSame(menu1, menu0);
  }
}
