/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 17:02:05 GMT 2024
 */

package TP1;

import org.junit.Test;
import static org.junit.Assert.*;
import TP1.ViewLogin;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class ViewLogin_ESTest extends ViewLogin_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ViewLogin viewLogin0 = new ViewLogin();
      viewLogin0.printMenuLogin();
  }
}
