/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 23:40:24 GMT 2024
 */

package TP2;

import org.junit.Test;
import static org.junit.Assert.*;
import TP2.EncomendaNaoEncontradaException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EncomendaNaoEncontradaException_ESTest extends EncomendaNaoEncontradaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EncomendaNaoEncontradaException encomendaNaoEncontradaException0 = new EncomendaNaoEncontradaException((String) null);
  }
}
