/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 17:51:34 GMT 2024
 */

package turma;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import turma.AlunoInexistenteException;

@RunWith(EvoRunner.class) 
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class AlunoInexistenteException_ESTest extends AlunoInexistenteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlunoInexistenteException alunoInexistenteException0 = new AlunoInexistenteException("");
  }
}
