/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 17:51:29 GMT 2024
 */

package turma;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import turma.NotaInvalidaException;

@RunWith(EvoRunner.class) 
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class NotaInvalidaException_ESTest extends NotaInvalidaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NotaInvalidaException notaInvalidaException0 = new NotaInvalidaException("eR");
  }
}
