/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 23:39:26 GMT 2024
 */

package TP2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import TP2.ComparatorVendas;
import TP2.Utilizador;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparatorVendas_ESTest extends ComparatorVendas_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparatorVendas comparatorVendas0 = new ComparatorVendas();
      Long long0 = new Long(0L);
      Utilizador utilizador0 = new Utilizador("Jg^{5*d%y*HyV$P}+", "TP2.ComparatorVendas", "aw$gR<Lbg}+;P(E?+:", long0, "TP2.ComparatorVendas");
      Utilizador utilizador1 = new Utilizador(utilizador0);
      int int0 = comparatorVendas0.compare(utilizador0, utilizador1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparatorVendas comparatorVendas0 = new ComparatorVendas();
      // Undeclared exception!
      try { 
        comparatorVendas0.compare((Utilizador) null, (Utilizador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TP2.ComparatorVendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparatorVendas comparatorVendas0 = new ComparatorVendas();
      Long long0 = new Long(0L);
      Utilizador utilizador0 = new Utilizador("Jg^{5*d%y*HyV$P}+", "TP2.ComparatorVendas", "aw$gR<Lbg}+;P(E?+:", long0, "TP2.ComparatorVendas");
      Utilizador utilizador1 = new Utilizador(utilizador0);
      utilizador1.setN_vendidos(3);
      int int0 = comparatorVendas0.compare(utilizador0, utilizador1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparatorVendas comparatorVendas0 = new ComparatorVendas();
      Long long0 = new Long(0L);
      Utilizador utilizador0 = new Utilizador("Jg^{5*d%y*HyV$P}+", "TP2.ComparatorVendas", "aw$gR<Lbg}+;P(E?+:", long0, "TP2.ComparatorVendas");
      Utilizador utilizador1 = new Utilizador(utilizador0);
      utilizador1.setN_vendidos(3);
      int int0 = comparatorVendas0.compare(utilizador1, utilizador0);
      assertEquals((-1), int0);
  }
}
