/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 23:40:33 GMT 2024
 */

package TP2;

import org.junit.Test;
import static org.junit.Assert.*;
import TP2.TransportadoraNaoEncontradaException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TransportadoraNaoEncontradaException_ESTest extends TransportadoraNaoEncontradaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TransportadoraNaoEncontradaException transportadoraNaoEncontradaException0 = new TransportadoraNaoEncontradaException("");
  }
}
