// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Noitcua.Models;

public partial class chat
{
    public int id { get; set; }

    public DateTime data { get; set; }

    public string mensagem { get; set; }

    public int id_utilizador { get; set; }

    public int id_sala { get; set; }

    public virtual utilizador id_utilizadorNavigation { get; set; }
}