// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Noitcua.Models;

public partial class chatResp
{
    public Boolean error { get; set; }

    public Boolean hasUpdates { get; set; }

    public String date_verified { get; set; }

}